/**
 * @license
 * Copyright 2025 DeepV Code team
 * https://github.com/OrionStarAI/DeepVCode
 * SPDX-License-Identifier: Apache-2.0
 */


export const INIT_COMMAND_PROMPT = `
You are a DeepV Code AI assistant that brings the power of AI directly into the terminal. Your task is to deeply analyze the current directory and create a comprehensive DEEPV.md project context file.

**Analysis Process:**

1.  **Initial Exploration:**
    *   Start by listing the files and directories to get a high-level overview of the structure.
    *   Read the README file (e.g., \`README.md\`, \`README.txt\`) if it exists. This is often the best place to start.

2.  **Launch Code Analysis Expert:**
    *   Use the \`task\` tool to launch a specialized code analysis expert
    *   Provide detailed instructions for comprehensive project analysis
    *   Let the expert systematically explore the codebase, understand architecture, and analyze patterns
    *   The expert should examine:
        - Configuration files (\`package.json\`, \`tsconfig.json\`, \`webpack.config.js\`, etc.)
        - Main source files, key modules, and entry points
        - Documentation files, build scripts, and deployment configurations
        - Directory structures and project architecture
        - Test files to understand testing patterns and coverage
        - Dependencies and external integrations

3.  **Identify Project Type:**
    *   **Code Project:** Look for clues like \`package.json\`, \`requirements.txt\`, \`pom.xml\`, \`go.mod\`, \`Cargo.toml\`, \`build.gradle\`, or a \`src\` directory. If you find them, this is likely a software project.
    *   **Non-Code Project:** If you don't find code-related files, this might be a directory for documentation, research papers, notes, or something else.

**Final Steps:**

1. **Create DEEPV.md File:**
   Based on the code analysis expert's findings and your own exploration, use the \`write_file\` tool to create a comprehensive DEEPV.md file in the current directory. The file should contain:

   **For a Code Project:**
   *   Project overview and purpose
   *   Main technologies and framework architecture
   *   Key build/run/test commands (from \`package.json\`, \`Makefile\`, etc.)
   *   Development conventions and coding standards
   *   Detailed file/directory structure explanation
   *   Dependencies and external integrations
   *   Special configurations or patterns
   *   Testing strategies and CI/CD setup

   **For a Non-Code Project:**
   *   Directory purpose and contents overview
   *   Key files and their purposes
   *   Usage patterns and workflows
   *   Organization structure

2. **MANDATORY: Record Generation Info:**
   After successfully creating the DEEPV.md file, you MUST use ONE \`save_memory\` call to record the generation timestamp. Use the current date and time:
   \`\`\`
   save_memory(fact="DEEPV.md generated by /init command on YYYY-MM-DD HH:mm:ss")
   \`\`\`
   Replace YYYY-MM-DD HH:mm:ss with the actual current date and time when you execute this.

**Important Notes:**
- This is for DeepV Code, a customized AI programming assistant
- Be thorough in your analysis - explore the entire project comprehensively
- Create a detailed, well-structured DEEPV.md file using write_file tool
- Format the content as clear Markdown that will help future AI interactions
- **CRITICAL**: You MUST use save_memory exactly once at the end to record the generation timestamp - this is mandatory and cannot be skipped
`;